### ISSUE TITLE
Build with  incompatible architecture ?

### ISSUE THREAD

**Issue by FMassin** [seiscomp-macOS/seiscomp#1]
Hello

Thank you so much for this project! Unfortunately, after following instructions and successful compilation, I am getting this : 
```bash
❯ seiscomp print env
Traceback (most recent call last):
  File "/Users/fred/seiscomp/bin/seiscomp-control.py", line 23, in <module>
    import seiscomp._config
ImportError: dlopen(/Users/fred/seiscomp/lib/python/seiscomp/_config.so, 0x0002): tried: '/Users/fred/seiscomp/lib/python/seiscomp/_config.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/fred/seiscomp/lib/python/seiscomp/_config.so' (no such file), '/Users/fred/seiscomp/lib/python/seiscomp/_config.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

Any help?

**Comment by FMassin** [comment]
I was missing 
```bash
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/bin:/usr/bin:/usr/sbin:$PATH
```
Now it works sorry. Please feel free to delete the issue.

**Comment by gilcel** [comment]
OK no problem...I'm glad it works now..but take a look at this issue, maybe it could help for the next errors :-)
https://github.com/seiscomp-macOS/main/issues/1

**Comment by FMassin** [comment]
Hey! I could also enable suport for iloc, sqlite3 and PostgreSQL. PostgreSQL required specification of the include dir and library (respectively `/opt/homebrew/Cellar/postgresql@14/14.11//include/postgresql@14/` and `/opt/homebrew/Cellar/postgresql@14/14.11//lib/postgresql@14/libpq.dylib` in my case) ... Maybe that a bonus that worth being in the README?

**Comment by gilcel** [comment]
Ah Merci! We've never tried with PostgreSQL (only MySQL) and yes iLoc works pretty well on macOS.

Will update README as soon as possible, also to remember that "seiscomp-macOS" prefers BASH shell instead of the now default "Zsh" on macOS...
